export const clinics = [
  'Proficient Rx LP',
  'CLINIQUE LABORATORIES INC',
  'Aruba Aloe Balm NV',
  'Reckitt Benckiser LLC',
  'Teva Pharmaceuticals USA Inc',
  'Mylan Institutional Inc.',
  'Unifirst First Aid Corporation',
  'REMEDYREPACK INC.',
  'L.N.K. International, Inc.',
  'Fresenius Kabi USA, LLC',
  'Altura Pharmaceuticals, Inc.',
  'Nelco Laboratories, Inc.',
  'ALK-Abello, Inc.',
  'Physicians Total Care, Inc',
  "Teva Women's Health, Inc.",
  'Atlantic Biologicals Corps',
  'Tris Pharma Inc',
  'International Beauty Exchange',
  "Dr.Reddy's laboratories Ltd.",
  'Par Pharmaceutical Inc.',
  'Georgia Oxygen & Home Health',
  'Gordon Laboratories',
  'Buckeye International, Inc.',
  'Hospira, Inc.',
  'Bare Escentuals Beauty Inc.',
  'PD-Rx Pharmaceuticals, Inc.',
  'Apple Products, Inc.',
  'sanofi-aventis U.S. LLC',
  'STAT RX USA LLC',
  'Lumene Oy',
  'Autumn Harp, Inc',
  'Paddock Laboratories, LLC',
  'Aaron Industries, Inc.',
  "Dr.Reddy's Laboratories Limited",
  'Publix Super Markets Inc',
  'Kareway Product, Inc.',
  'Torrent Pharmaceuticals Limited',
  'A&Z Pharmaceutical, Inc.',
  'GREENBRIER INTERNATIONAL, INC.',
  'The Body Shop Wake Forest',
  'CVS Pharmacy, Inc',
  'J. A. Cosmetics U.S. INC',
  'HYVEE INC',
  'Carilion Materials Management',
  'Cardinal Health',
  'Isomers Laboratories Inc',
  'Mylan Institutional Inc.',
  'Rebel Distributors Corp.',
  'GlaxoSmithKline LLC',
  'Hannaford Brothers Company',
  'ProPhase Labs, Inc.',
  'Kosan Kozmetik Sanayi ve Ticaret A.S.',
  'Physicians Total Care, Inc.',
  'Autumn Harp, Inc',
  'Total Resources International',
  'Greenbrier International, Inc.',
  'Navarro Discount Pharmacies, LLC',
  'Nelco Laboratories, Inc.',
  'Unit Dose Services',
  'Deb USA, Inc.',
  'Apotex Corp.',
  'Fortune Hi-Tech',
  'Pharmacia and Upjohn Company',
  'ALK-Abello, Inc.',
  'New Sun Inc.',
  'Humex,Inc.',
  'Braintree Laboratories, Inc.',
  'Supervalu Inc',
  'Walgreen Company',
  'REMEDYREPACK INC.',
  'Sandoz Inc',
  'Major Pharmaceuticals',
  'Uriel Pharmacy Inc',
  'Kroger Company',
  'Cardinal Health',
  'Nelco Laboratories, Inc.',
  'Certus Medical, Inc.',
  'JF Labs, Inc.',
  'Walgreens',
  'Mineral Fusion Natural Brands LLC',
  'Cardinal Health',
  'McKesson',
  'Crown Products, LLC',
  'Walgreen Company',
  'Actavis Elizabeth LLC',
  'Antigen Laboratories, Inc.',
  "Tom's of Maine, Inc.",
  'WH Nutritionals, LLC',
  'PD-Rx Pharmaceuticals, Inc.',
  'Geiss, Destin & Dunn, Inc.',
  'Apotheca Company',
  'NATURE REPUBLIC CO., LTD.',
  'MSD Consumer Care, Inc.',
  'Rebel Distributors Corp',
  'REMEDYREPACK INC.',
  'PUR MINERALS',
  'Wockhardt Limited',
  'Amerifoods Trading Company',
  'Everett Laboratories, Inc.',
  'Topco Associates',
];
